drop table cmakers;
commit;
set escape on

CREATE TABLE CMAKERS
(
CID int NOT NULL PRIMARY KEY,
MAKER varchar(60) NOT NULL,
MSHORT char(3) NOT NULL
);

/* INSERT INTO CMAKERS VALUES (1, 'AMERICAN MOTORS', 'AMC');
INSERT INTO CMAKERS VALUES (2, 'AUDI', 'AUD');
INSERT INTO CMAKERS VALUES (3, 'BMW', 'BMW');
INSERT INTO CMAKERS VALUES (8, 'DODGE', 'DOD');
INSERT INTO CMAKERS VALUES (9, 'DODGE/PLYMOUTH LITE TRK \& VAN', 'DOT');
INSERT INTO CMAKERS VALUES (11, 'FORD MEDIUM AND HEAVY TRUCK', 'FDM');
INSERT INTO CMAKERS VALUES (12, 'FIAT', 'FIA');
INSERT INTO CMAKERS VALUES (36, 'GMC TRUCK AND VAN', 'GMM');
INSERT INTO CMAKERS VALUES (15, 'HONDA', 'HON');
INSERT INTO CMAKERS VALUES (34, 'HYUNDAI', 'HUN');
INSERT INTO CMAKERS VALUES (19, 'MERCEDES', 'MCS');
INSERT INTO CMAKERS VALUES (20, 'MITSUBISHI', 'MIT');
INSERT INTO CMAKERS VALUES (21, 'MERCURY', 'MRY');
INSERT INTO CMAKERS VALUES (23, 'NISSAN / DATSUN', 'NIS');
INSERT INTO CMAKERS VALUES (25, 'PLYMOUTH', 'PLY');
INSERT INTO CMAKERS VALUES (27, 'PONTIAC', 'PON');
INSERT INTO CMAKERS VALUES (35, 'YUGO', 'YUG'); */

INSERT INTO CMAKERS VALUES (4, 'BUICK', 'BUK');
INSERT INTO CMAKERS VALUES (5, 'CADILLAC', 'CAD');
INSERT INTO CMAKERS VALUES (6, 'CHEVROLET', 'CHE');
INSERT INTO CMAKERS VALUES (7, 'CHRYSLER', 'CRY');
INSERT INTO CMAKERS VALUES (10, 'FORD LIGHT TRUCK AND VAN', 'FDT');
INSERT INTO CMAKERS VALUES (13, 'FORD', 'FOR');
INSERT INTO CMAKERS VALUES (14, 'CHEVROLET \& GMC TRUCK \& VAN', 'GMC');
INSERT INTO CMAKERS VALUES (16, 'INTERNATIONAL TRUCK (I.H.C.)', 'INT');
INSERT INTO CMAKERS VALUES (17, 'ISUZU', 'ISU');
INSERT INTO CMAKERS VALUES (18, 'LINCOLN', 'LIN');
INSERT INTO CMAKERS VALUES (22, 'MAZDA', 'MZD');
INSERT INTO CMAKERS VALUES (24, 'OLDSMOBILE', 'OLD');
INSERT INTO CMAKERS VALUES (26, 'PORSCHE', 'POR');
INSERT INTO CMAKERS VALUES (28, 'RENAULT', 'REN');
INSERT INTO CMAKERS VALUES (29, 'SAAB', 'SAB');
INSERT INTO CMAKERS VALUES (30, 'SUBARU', 'SUB');
INSERT INTO CMAKERS VALUES (31, 'TOYOTA', 'TOY');
INSERT INTO CMAKERS VALUES (32, 'UPS', 'UPS');
INSERT INTO CMAKERS VALUES (33, 'VOLKSWAGEN', 'VOL');

commit;
set escape off