drop table partmakers;
commit;

CREATE TABLE PARTMAKERS
(
name varchar(30) NOT NULL PRIMARY KEY);

 -- INSERT INTO PARTMAKERS VALUES ('RADCRX'); 
INSERT INTO PARTMAKERS VALUES ('RDIMARS');
INSERT INTO PARTMAKERS VALUES ('RDIMBEH');
INSERT INTO PARTMAKERS VALUES ('RDIMDAN');
INSERT INTO PARTMAKERS VALUES ('RDIMMOD');